
storageSettings:
  defaultStorge: example_outputs
  defaultFormat: CSV

storage:

  example_inputs:

    storageType: LOCAL_STORAGE
    storageConfig:
      rootPath: ./data/inputs

  example_outputs:

    storageType: LOCAL_STORAGE
    storageConfig:
      rootPath: ./data/outputs


sparkSettings:

  sparkConfig:
    [spark.cores.max]: 4
    [spark.driver.memory]: 2G
    [spark.executor.memory]: 2G
    [spark.default.parallelism]: 8
    [spark.sql.shuffle.partitions]: 8
