name: Basic Build

on: [push, pull_request]

jobs:

  platform_build:

    runs-on: ubuntu-latest

    steps:

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.x
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: ./gradlew build -x test

    - name: Unit tests
      run: ./gradlew test

  python_executor_build:

    runs-on: ubuntu-latest

    # Testing targets for the Python executor runtime
    # Include the latest stable release (3.9)
    # Include the oldest supported release in the 3.X family
    # Do not include 2.7 - that ship has sailed!
    strategy:
      matrix:
        python-version: [3.9, 3.5]

    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd trac-executors/python
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Protoc Code Generation
        run: |
          cd trac-executors/python
          python codegen/pythonic.py --protoc
          python codegen/pythonic.py --pythonic

      - name: Unit tests
        run: |
          cd trac-executors/python
          python -m unittest -s test/trac_test -t test
